### ISSUE TITLE
ngab izin comot

### ISSUE THREAD

**Issue by hnvdie** [kereh/kereh#1]

**Comment by hnvdie** [comment]
Ga dibales gais

**Comment by kereh** [comment]
> Ga dibales gais

wkwkwk silahkan mas, maaf bru bales soalnya bru buka email ama github

**Comment by hnvdie** [comment]
> > Ga dibales gais
> 
> wkwkwk silahkan mas, maaf bru bales soalnya bru buka email ama github

anjay berattitude 😎

**Comment by kereh** [comment]
> > > Ga dibales gais
> > 
> > 
> > wkwkwk silahkan mas, maaf bru bales soalnya bru buka email ama github
> 
> anjay berattitude 😎

woiya donk
