### ISSUE TITLE
Kodok zuma Append requests - Primary question

### ISSUE THREAD

**Issue by hnvdie** [kereh/kereh#2]
Hey thomas shelby can you add this one

![png-clipart-smiley-emoticon-animation-thug-life-miscellaneous-heart](https://github.com/user-attachments/assets/56952047-8e26-43fb-8848-4df150559060)

**Comment by kereh** [comment]
what the foook, who the hell is this

**Comment by hnvdie** [comment]
> what the foook, who the hell is this

bilek amat bejir, mabar game baru delta force

**Comment by hnvdie** [comment]
jir github issue rasa forum messenger

**Comment by kereh** [comment]
delta force mobile?

**Comment by hnvdie** [comment]
> delta force mobile?

ada dua mobile iya, console iya jg. tapi yg console msh demo jir. main yg mobel dulu sabi. chat wa coy nanti gw tutorin install nya yg versi cina

**Comment by hnvdie** [comment]
> delta force mobile?
issue nya di open lagi aowkwowk 🗿
![download](https://github.com/user-attachments/assets/8e198f95-aece-44ac-b1e7-9e8c9fcd9f39)

**Comment by kereh** [comment]
pke wa ngapa sih anjm, hrus bgt di open issue

**Comment by hnvdie** [comment]
> pke wa ngapa sih anjm, hrus bgt di open issue

wa luh kaga aktif anjim

**Comment by hnvdie** [comment]
![Screenshot_2024-11-08-19-02-07-560_com tencent tmgp dfm](https://github.com/user-attachments/assets/02612af3-63e0-4b4b-9ec0-2a799ad3e1da)

enak ko coy yg cina, sama aja command nya kaya game codm, etc. bahasa aja doang yg cina, ga ngaruh ke gameplay.

**Comment by kereh** [comment]
wa lu yg gk aktif

**Comment by kereh** [comment]
blm official rilis bjir

**Comment by hnvdie** [comment]
> wa lu yg gk aktif

chat

**Comment by hnvdie** [comment]
> blm official rilis bjir

udh lama official jir diregion cina, yg full msh demo.

**Comment by kereh** [comment]
> > wa lu yg gk aktif
> 
> chat

![Screenshot_2024-11-08-19-06-17-64_6012fa4d4ddec268fc5c7112cbb265e7](https://github.com/user-attachments/assets/e011af9b-5c58-42d5-9ff7-5659edfaa1ff)

gk ad yng aktif

**Comment by hnvdie** [comment]
> > > wa lu yg gk aktif
> > 
> > 
> > chat
> 
> ![Screenshot_2024-11-08-19-06-17-64_6012fa4d4ddec268fc5c7112cbb265e7](https://private-user-images.githubusercontent.com/38828786/384344669-e011af9b-5c58-42d5-9ff7-5659edfaa1ff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjQzMzAsIm5iZiI6MTczMTA2NDAzMCwicGF0aCI6Ii8zODgyODc4Ni8zODQzNDQ2NjktZTAxMWFmOWItNWM1OC00MmQ1LTlmZjctNTY1OWVkZmFhMWZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMDcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNmIzYTNiZjMwNzQ1ZTU4ODUzYjE2MjVkOWU5ZjllZTIyZjlhOWU1YjAyZjQ2N2Y4MTkzMDUwNDk5NjU3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yh6K1lyd2_GJ9srr7XeCwctseuGPK3RYi3l8OLPp_1I)
> 
> gk ad yng aktif

ez doxing jir di screenshot

**Comment by hnvdie** [comment]
ngab contribin https://github.com/hnvdie/CryptoSentimentAnalyzer based via web scraping buat grab article > analisis potensial beritanya.
